---
site_name: JARVYS_DEV
nav:
  - Home: index.md
  - API Reference:
      - Jarvys Dev: modules/jarvys_dev.md
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: false
