[tool.poetry]
name = "jarvys-dev"
version = "0.1.0"
description = "Autonomous Dev agent"
authors = ["Yann Abadie <yannabadie@example.com>"]
packages = [{ include = "jarvys_dev", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
PyGithub = "^2.6"
requests = "^2"

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pytest-mock = "^3.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"